/*
 * To change this license header, choose License Headers in Project Properties. To change this
 * template file, choose Tools | Templates and open the template in the editor.
 */
package payroll.employee;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.Base64;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.config.cConfig;

/**
 *
 * @author gerald
 */
public class generateEmployeePaycheckSlip extends javax.swing.JFrame {
        private String employeeId;

        /**
         * Creates new form generateEmployeePaycheckSlip
         */
        public generateEmployeePaycheckSlip() {
                initComponents();
                Toolkit toolkit = getToolkit();
                Dimension size = toolkit.getScreenSize();
                setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                txt_firstName.setEditable(false);
                txt_lastName.setEditable(false);
                txt_dateOfBirth.setEditable(false);
                txt_department.setEditable(false);
                txt_jobTitle.setEditable(false);
                txt_status.setEditable(false);
                txt_dateHired.setEditable(false);
                txt_basicSalary.setEditable(false);
        }


        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT
         * modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel6 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                txt_employeeID = new javax.swing.JTextField();
                txt_firstName = new javax.swing.JTextField();
                txt_lastName = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                txt_dateOfBirth = new javax.swing.JTextField();
                txt_jobTitle = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                txt_status = new javax.swing.JTextField();
                txt_dateHired = new javax.swing.JTextField();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel10 = new javax.swing.JLabel();
                txt_basicSalary = new javax.swing.JTextField();
                jLabel12 = new javax.swing.JLabel();
                txt_department = new javax.swing.JTextField();
                button_generateSlip = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
                jLabel6.setText("Print Paycheck Slip");

                jLabel1.setText("Enter Employee ID:");

                txt_employeeID.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_employeeIDActionPerformed(evt);
                        }
                });

                txt_firstName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_firstNameActionPerformed(evt);
                        }
                });

                txt_lastName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_lastNameActionPerformed(evt);
                        }
                });

                jLabel3.setText("Last Name:");

                jLabel4.setText("First Name:");

                jLabel5.setText("Date of birth:");

                txt_dateOfBirth.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_dateOfBirthActionPerformed(evt);
                        }
                });

                txt_jobTitle.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_jobTitleActionPerformed(evt);
                        }
                });

                jLabel7.setText("Job Title:");

                txt_status.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_statusActionPerformed(evt);
                        }
                });

                txt_dateHired.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_dateHiredActionPerformed(evt);
                        }
                });

                jLabel8.setText("Date Hired:");

                jLabel9.setText("Status:");

                jLabel10.setText("Basic Salary:");

                txt_basicSalary.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_basicSalaryActionPerformed(evt);
                        }
                });

                jLabel12.setText("Department:");

                txt_department.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_departmentActionPerformed(evt);
                        }
                });

                button_generateSlip.setText("Generate Slip");
                button_generateSlip.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                button_generateSlipActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addGap(168, 168,
                                                                                                168)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addComponent(jLabel3))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(txt_firstName)
                                                                                                                                                .addComponent(txt_lastName,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                211,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(txt_dateOfBirth,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                213,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel12)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(txt_department,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                211,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                190,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                .addComponent(jLabel9)
                                                                                                                                .addComponent(jLabel8))
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                                .addComponent(txt_status)
                                                                                                                                .addComponent(txt_dateHired,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                211,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel10)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(txt_basicSalary,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                211,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel7)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(txt_jobTitle,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                211,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addContainerGap(
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jLabel1)
                                                                                .addGap(44, 44, 44)
                                                                                .addComponent(txt_employeeID,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                206,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(310, 310,
                                                                                                310)))
                                                .addGap(181, 181, 181))
                                .addGroup(layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel6)
                                                .addContainerGap(788, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addContainerGap(
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                .addComponent(button_generateSlip,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                277,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(77, 77, 77)));
                layout.setVerticalGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap()
                                                .addGroup(layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel6,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                63,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(38, 38, 38)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel1)
                                                                                                .addComponent(txt_employeeID,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(87, 87, 87)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel7)
                                                                                                .addComponent(txt_jobTitle,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel9)
                                                                                                .addComponent(txt_status,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel8)
                                                                                                .addComponent(txt_dateHired,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel10)
                                                                                                .addComponent(txt_basicSalary,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel4)
                                                                                                .addComponent(txt_firstName,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel3)
                                                                                                .addComponent(txt_lastName,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel5)
                                                                                                .addComponent(txt_dateOfBirth,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel12)
                                                                                                .addComponent(txt_department,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                164, Short.MAX_VALUE)
                                                .addComponent(button_generateSlip,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                104,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(52, 52, 52)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void button_checkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_button_checkActionPerformed
                // TODO add your handling code here:

        }// GEN-LAST:event_button_checkActionPerformed

        private void button_generateSlipActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_button_generateSlipActionPerformed
                // TODO add your handling code here:

                // generate slip

                String firstName = txt_firstName.getText();
                String lastName = txt_lastName.getText();
                String id = txt_employeeID.getText();
                String jobTitle = txt_jobTitle.getText();

                JFileChooser dialog = new JFileChooser();
                dialog.setSelectedFile(
                                new File(firstName + " " + lastName + "-Salary Slip" + ".pdf"));
                int dialogResult = dialog.showSaveDialog(null);

                String filePath = dialog.getSelectedFile().getPath();

                try {

                } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                }
        }// GEN-LAST:event_button_generateSlipActionPerformed

        private void txt_firstNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_firstNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_firstNameActionPerformed

        private void txt_jobTitleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_jobTitleActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_jobTitleActionPerformed

        private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_lastNameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_lastNameActionPerformed

        private void txt_dateOfBirthActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_dateOfBirthActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_dateOfBirthActionPerformed

        private void txt_departmentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_departmentActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_departmentActionPerformed

        private void txt_statusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_statusActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_statusActionPerformed

        private void txt_dateHiredActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_dateHiredActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_dateHiredActionPerformed

        private void txt_basicSalaryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_basicSalaryActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_basicSalaryActionPerformed

        private void txt_employeeIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_employeeIDActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txt_employeeIDActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look
                 * and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger
                                        .getLogger(generateEmployeePaycheckSlip.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger
                                        .getLogger(generateEmployeePaycheckSlip.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger
                                        .getLogger(generateEmployeePaycheckSlip.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger
                                        .getLogger(generateEmployeePaycheckSlip.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new generateEmployeePaycheckSlip().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton button_generateSlip;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JTextField txt_basicSalary;
        private javax.swing.JTextField txt_dateHired;
        private javax.swing.JTextField txt_dateOfBirth;
        private javax.swing.JTextField txt_department;
        private javax.swing.JTextField txt_employeeID;
        private javax.swing.JTextField txt_firstName;
        private javax.swing.JTextField txt_jobTitle;
        private javax.swing.JTextField txt_lastName;
        private javax.swing.JTextField txt_status;
        // End of variables declaration//GEN-END:variables
}
