/*
 * To change this license header, choose License Headers in Project Properties. To change this
 * template file, choose Tools | Templates and open the template in the editor.
 */
package payroll.employee;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import com.config.cConfig;
import com.view.cView;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import model.*;

/**
 *
 * @author gerald
 */
public class payment extends javax.swing.JFrame {
    String position;
    String empId;
    String basicSalry;
    String monthSalary;
    // Generate a random 10-digit positive integer

    /**
     * Creates new form registerEmployee
     */
    public payment() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        field_cardName.setEditable(false);
        field_cardNumber.setEditable(false);
        field_holderName.setEditable(false);
        field_name.setEditable(false);

        txt_defaultPassword.setEditable(false);
        txt_email.setEditable(false);
        txt_employeeID.setEditable(false);
        
        
    }

    public void getEmployeeId(String empEmail) {

        String employeeId = cConfig.getEmployeeIdByEmail(empEmail);

        Map<String, String> employeeAccountData = cConfig.getAccountDataById(employeeId);

        String defaultPassword = employeeAccountData.get("password");
        txt_defaultPassword.setText(defaultPassword != null ? defaultPassword : "");

        // Set nilai pada JTextField field_name
        String name = employeeAccountData.get("name");
        field_name.setText(name != null ? name : "");


        Map<String, String> employeeCardData = cConfig.getCardDataById(employeeId);
        String cardName = employeeCardData.get("card_holder_name");
        field_cardName.setText(cardName != null ? cardName : "");

        // Set nilai pada JTextField field_cardNumber
        String cardNumber = employeeCardData.get("card_number");
        field_cardNumber.setText(cardNumber != null ? cardNumber : "");

        // Set nilai pada JTextField field_holderName
        String holderName = employeeCardData.get("card_holder_name");
        field_holderName.setText(holderName != null ? holderName : "");

        String salary = employeeCardData.get("salary");
        int totalAttendances = cConfig.countAttendances(employeeId);
        
        
        DecimalFormat decimalFormat = new DecimalFormat("#,###.###");

        // Menggunakan DecimalFormat untuk memformat angka
        String formattedBasicSalary = decimalFormat.format(Integer.parseInt(salary));
        
        LocalDate lastMonth = LocalDate.now().minusMonths(1);

        // Mendapatkan jumlah hari pada bulan lalu
        int lastMonthDays = YearMonth.from(lastMonth).lengthOfMonth();
        
        double attendancePercentage = (double) totalAttendances / lastMonthDays;
        String formattedMonthSalary = decimalFormat.format(Double.parseDouble(salary) * attendancePercentage );
        
        salary_label.setText(
                salary != null ? "Rp."+formattedMonthSalary : "");
        
        

        
        this.basicSalry = formattedBasicSalary;
        this.monthSalary = formattedMonthSalary;

        txt_employeeID.setText(employeeId);
        txt_email.setText(empEmail);



    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    public JTextField getTxtEmployeeID() {
        return txt_employeeID;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_employeeID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_defaultPassword = new javax.swing.JTextField();
        field_cardName = new javax.swing.JTextField();
        field_holderName = new javax.swing.JTextField();
        field_cardNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        field_name = new javax.swing.JTextField();
        button_print = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        salary_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Employee ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("Payment");

        txt_employeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_employeeIDActionPerformed(evt);
            }
        });

        jLabel9.setText("Email:");

        jLabel10.setText("Password:");

        jLabel2.setText("Card Name : ");

        jLabel3.setText("Card Holder Name :");

        jLabel4.setText("Card Number :");

        jLabel5.setText("Name :");

        button_print.setText("Save Paycheck Slip");
        button_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_printActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Salary This Month : ");

        salary_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salary_label.setText("gaji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(58, 58, 58).addGroup(layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3).addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(field_cardNumber,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195).addComponent(button_print,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, 171,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addGroup(layout.createSequentialGroup().addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(field_holderName,
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_employeeID,
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 250,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel1,
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(field_cardName,
                                                javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel2)).addGap(169, 169, 169)
                                .addGroup(layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9).addComponent(jLabel5)
                                        .addComponent(txt_email,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 253,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_defaultPassword,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10).addComponent(field_name,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 250,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        153, Short.MAX_VALUE)
                                .addGroup(layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(salary_label)
                                                        .addGap(10, 10, 10)))))
                        .addGap(168, 168, 168)));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGroup(layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(30, 30, 30)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1).addComponent(jLabel5))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addContainerGap()
                                        .addComponent(jLabel7).addGap(2, 2, 2)))
                        .addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_employeeID,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addGap(7, 7, 7)
                                        .addGroup(layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2).addComponent(jLabel9)))
                                .addGroup(layout.createSequentialGroup().addGap(12, 12, 12)
                                        .addComponent(salary_label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(field_cardName,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3).addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(field_holderName,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_defaultPassword,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40).addComponent(jLabel4).addGap(18, 18, 18)
                        .addGroup(layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(field_cardNumber,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button_print, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(265, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_printActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_button_printActionPerformed
        // TODO add your handling code here:
        LocalDate currentDate = LocalDate.now();

        // Mendapatkan hari dalam sebulan
        int dayOfMonth = currentDate.getDayOfMonth();

        // Mengecek apakah tanggal berada dalam rentang 1-5
        if (dayOfMonth >= 1 && dayOfMonth <= 2) {
            
             try {
                // Menghitung 1 bulan sebelumnya
                LocalDate lastMonthDate = currentDate.minusMonths(1);

                // Mengonversi ke dalam format nama bulan
                DateTimeFormatter monthFormatter = DateTimeFormatter.ofPattern("MMMM");
                String lastMonth = lastMonthDate.format(monthFormatter);
                // Create a new document
                PDDocument document = new PDDocument();

                // Add a page to the document
                PDPage page = new PDPage();
                document.addPage(page);

                // Create content stream for the page
                PDPageContentStream contentStream = new PDPageContentStream(document, page);

                // Add text to the PDF
                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD_OBLIQUE), 18);
                contentStream.newLineAtOffset(100, 750);
                contentStream.showText("Paycheck Salary for " + lastMonth);

                // Set font for the details
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                contentStream.newLineAtOffset(20, -50);
                contentStream.showText("Employee ID: " + txt_employeeID.getText());
                contentStream.newLineAtOffset(0, -25);
                contentStream.showText("Name: " + field_name.getText());
                contentStream.newLineAtOffset(0, -25);
                contentStream.showText("Card Name: " + field_cardName.getText());
                contentStream.newLineAtOffset(0, -25);
                contentStream.showText("Card Holder Name: " + field_holderName.getText());
                contentStream.newLineAtOffset(0, -25);
                contentStream.showText("Card Number: " + field_cardNumber.getText());
                contentStream.newLineAtOffset(0, -25);
                contentStream.showText("Basic Monthly Salary: Rp." + this.basicSalry);
                contentStream.newLineAtOffset(0, -25);
                contentStream.showText("Salary this Month: Rp." + this.monthSalary);
                contentStream.endText();

                // Close the content stream
                contentStream.close();

                // Save the document to a file
                String path = field_name.getText() +"_Month("+ lastMonth +").pdf";
                document.save("PaychekSlip/"+path);

                // Close the document
                document.close();

                 JOptionPane.showMessageDialog(null, "Successfully Save the Paycheck Slip.", "Success", JOptionPane.INFORMATION_MESSAGE);
                 this.dispose();

            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "You can only print check slips in the 1-2 date range!", "WARNING!", JOptionPane.INFORMATION_MESSAGE);
        }
       
    }// GEN-LAST:event_button_printActionPerformed

    private void radio_managerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_radio_managerActionPerformed
        // TODO add your handling code here:
        position = "Manager";

    }// GEN-LAST:event_radio_managerActionPerformed

    private void radio_workerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_radio_workerActionPerformed
        // TODO add your handling code here:
        position = "Worker";
    }// GEN-LAST:event_radio_workerActionPerformed



    private void txt_employeeIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txt_employeeIDActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txt_employeeIDActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and
         * feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_print;
    private javax.swing.JTextField field_cardName;
    private javax.swing.JTextField field_cardNumber;
    private javax.swing.JTextField field_holderName;
    private javax.swing.JTextField field_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel salary_label;
    private javax.swing.JTextField txt_defaultPassword;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_employeeID;
    // End of variables declaration//GEN-END:variables

    private String gender;
    private ImageIcon format = null;
    String filename = null;
    byte[] person_Image = null;
    InputStream profilePhoto;
}
